In [1]:
import pandas as pd
import numpy as np 
import os # if we want to change the path then we can use os 

In [2]:
# df = pd.read_csv('file_I cannot upload here because it is more than 94 mb and i cannot commit in github')

# Fake News Classification using LSTM

In [ ]:
df.head()

In [ ]:
# Drop Nan values
df = df.dropna()

In [ ]:
# Getting the independent features 
# here label column is the values like 1 and 0 which is dependent and other than that is indpendent features
X = df.drop('label', axis = 1)

In [ ]:
# Getting dependent features
y = df['label']


# Checking the shape of dependent and independent features

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
import tensorflow as tf
tf.__version__

In [ ]:
from tensorflow.keras.layers import Embedding, LSTM

# Embedding : when computer doesn't know text, in nlp we convert the text into a kind of number and number to vector and vector is 
# a kind of representation of different words in sentences and for this we need Embedding

from tensorflow.keras.preprocessing.sequence import pad_sequences 
# we need preprocessing because we need the lenght of sequence as same 




In [ ]:
messages = X.copy()

# checking how the text look like 

messages['title'][1]

In [ ]:
# resetting the index 
messages.reset_index(inplace = True)

In [ ]:
messages.head(10)

In [ ]:
import nltk 
import re
from nltk.corpus import stopwords

In [ ]:
# Dataset preprocessing 
from nltk.stem.porter import PorterStemmer
corpus = []

stemmer = PorterStemmer()
for i in range(0, len(messages)):
    sent = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    sent = sent.lower()
    sent = sent.split()

    sent = [stemmer.stem(word) for word in sent if not word in stopwords.words('english')]
    sent = ' '.join(sent)
    corpus.append(sent)

print(corpus)

In [ ]:
stopwords.words('english')

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot
voc_size = 1000000   # vocabulary size
onehot_repe = [one_hot(words, voc_size) for words in corpus]
onehot_repe

# Performing padding

In [ ]:
embedded_doc = pad_sequences(onehot_repe, maxlen = 100, padding = 'post')

In [ ]:
print(embedded_doc)

In [ ]:
# Creating Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


embedding_vector_features = 50

model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = 100))
model.add(LSTM(32))
model.add(Dense(1, actication = 'sigmoid'))

model.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrices = ['accuracy'] )

In [ ]:
X_input = np.array(embedded_doc)
y_input = np.array(y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_input, y_input, test_size= 0.2, random_state = 42 )

In [ ]:
X_train.shape

In [ ]:
y_train.shape

In [ ]:
X_test.shape

In [ ]:
y_test.shape

In [ ]:
# fitting and training the data 
model.fit(X_train, y_train, epochs = 5, batch_size = 64, validation_data = X_test, y_test)

# Epochs : suppose we have 50K data and this 50K data will go forward and backward pass for 5 times 
# the model will train the total data for 5 times 

# validation data is basically used as a try run your model and check it's performance before giving real world test data. 
# while validation data we can fine tune our model using hyperparameters

In [ ]:
# Prediction / checking the performance 


y_pred = model.predict(X_test)> 0.5).astype("int64")
y_pred.shape

In [ ]:
y_pred

In [ ]:
y_pred.unique()

In [3]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

NameError: name 'y_test' is not defined

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

# Bi- Directional LSTM 

# Creating Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional


embedding_vector_features = 50

model_bidirectional_lstm = Sequential()
model_bidirectional_lstm.add(Embedding(voc_size, embedding_vector_features, input_length = 100))
model_bidirectional_lstm.add(Bidirectional(LSTM(32))
model_bidirectional_lstm.add(Dense(1, activation = 'sigmoid'))

model_bidirectional_lstm.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrices = ['accuracy'] )
model_bidirectional_lstm.summary()

In [ ]:
model_bidirectional_lstm.fit(X_train, y_train, epochs = 5, batch_size = 64, validation_data = (X_test, y_test))

In [ ]:
# Prediction
y_pred = (model_bidirectional_lstm.predict(X_test)> 0.5).astype("int64")
y_pred.shape

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

# Rnn Implementation 

In [ ]:
# Creating Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN


embedding_vector_features = 50

model_rnn = Sequential()
model_rnn.add(Embedding(voc_size, embedding_vector_features, input_length = 100))
model_rnn.add(SimpleRNN(32))
model_rnn.add(Dense(1, activation = 'sigmoid'))

model_rnn.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrices = ['accuracy'] )
model_rnn.summary()

In [ ]:
model_rnn.fit(X_train, y_train, epochs = 5, batch_size = 64, validation_data = (X_test, y_test))

In [ ]:
# Prediction
y_pred = (model_rnn.predict(X_test)> 0.5).astype("int64")
y_pred.shape

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

# Bidirectional RNN

In [ ]:
# Creating Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, SimpleRNN, Bidirectional


embedding_vector_features = 50

model_bidirectional_rnn = Sequential()
model_bidirectional_rnn.add(Embedding(voc_size, embedding_vector_features, input_length = 100))
model_bidirectional_rnn.add(Bidirectional(SimpleRNN(32)))
model_bidirectional_rnn.add(Dense(1, activation = 'sigmoid'))

model_bidirectional_rnn.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrices = ['accuracy'] )
model_bidirectional_rnn.summary()

In [ ]:
model_bidirectional_rnn.fit(X_train, y_train, epochs = 5, batch_size = 64, validation_data = (X_test, y_test))

In [ ]:
# Prediction
y_pred = (model_bidirectional_rnn.predict(X_test)> 0.5).astype("int64")
y_pred.shape

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

In [ ]:
#Comparing different confusion matrix
LSTM
array([[3119,  300],
       [ 219, 2397]])

bi-LSTM
array([[3115,  304],
       [ 231, 2385]])

RNN
array([[2999,  420],
       [  84, 2532]])


bi-RNN
array([[3129,  290],
       [ 238, 2378]])

In [ ]:
# Dropout :   In case of large architecture, it will have high number of hidden layer so this leads to overfitting so to 
# get rid of overfitting we add dropout 

In [ ]:
# Dropout


# Creating Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Dense, LSTM, Dropout


embedding_vector_features = 50

model4 = Sequential()
model4.add(Embedding(voc_size, embedding_vector_features, input_length = 100))
model4.add(Dropout(0.3)) # here 30 % of the hidden layer will drop out 
model4.add(LSTM(100))
model4.add(Dropout(0.3))
model4.add(Dense(1, activation = 'sigmoid'))

model4.compile(loss = 'binary_crossentropy' , optimizer = 'adam' , metrices = ['accuracy'] )
model4.summary()

In [ ]:
model4.fit(X_train, y_train, epochs = 5, batch_size = 64, validation_data = (X_test, y_test))

In [ ]:
# Prediction
y_pred = (model4.predict(X_test)> 0.5).astype("int64")
y_pred.shape

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)